name: API Academy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14 # ajuste a versão do Node.js conforme necessário

      - name: Check versions of Newman and Node
        run: |
          newman --version
          node --version

      - name: Install Newman-Reporter-HtmlExtra
        run: npm install -g newman-reporter-htmlextra

      - name: Execute collection
        run: |
          newman run ./convergentes.postman_collection.json -g ./workspace.postman_globals.json -e ./convergentes.postman_environment.json --delay-request 1 --reporters cli, -r htmlextra --reporter-htmlextra-export ./result/Report.html

      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./result/Report.html
